CREATE TABLE myapp.solution
(
    id varchar(36) PRIMARY KEY NOT NULL,
    version bigint(20) NOT NULL,
    tieu_de varchar(1000),
    is_deleted bit(1),
    ngay_tao datetime,
    last_modified_user varchar(255),
    noi_dung_chi_tiet text,
    hinh_anh varchar(1000),
    noi_dung_ngan text,
    last_modified_time datetime,
    phone varchar(255),
    address varchar(1000),
    comment varchar(1000),
    name varchar(1000),
    email varchar(255)
);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('09b1999d-5d5d-49c9-9909-a9536002e035', 0, 'Giải pháp an ninh sử dụng Smart Line Series của Optex', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh sử dụng Smart Line Series của Optex</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2338</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>Hiện nay việc sử dụng h&agrave;ng r&agrave;o quang điện (Photoelectric Detector) dạng Beam trong c&aacute;c hệ thống b&aacute;o động chống đột nhập cho c&aacute;c khu vực rộng, y&ecirc;u cầu an ninh cao như khu c&ocirc;ng nghiệp, nh&agrave; m&aacute;y, khu vực qu&acirc;n sự, s&acirc;n bay, bến cảng,&hellip;ng&agrave;y c&agrave;ng phổ biến. C&aacute;c cảm biến h&agrave;ng r&agrave;o quang điện cho ph&eacute;p đưa ra c&aacute;c cảnh b&aacute;o nhanh tới trung t&acirc;m an ninh khi c&oacute; đối tượng đi ngang qua c&aacute;c tia hồng ngoại đ&oacute;ng vai tr&ograve; như h&agrave;ng r&agrave;o ảo. Một trong những vẫn đề khi sử dụng h&agrave;ng r&agrave;o quang điện hay gặp phải l&agrave; hiện tượng b&aacute;o động giả từ m&ocirc;i trường xung quanh như động vật, c&acirc;y cối, &aacute;nh s&aacute;ng mặt trời cũng như &aacute;nh s&aacute;ng nh&acirc;n tạo. Hiểu r&otilde; vấn đề n&agrave;y, OPTEX một c&ocirc;ng ty chuy&ecirc;n nghi&ecirc;n cứu v&agrave; sản xuất cảm biến cho hệ thống b&aacute;o động đ&atilde; giới thiệu d&ograve;ng sản phẩm h&agrave;ng r&agrave;o quang điện thế hệ mới &ndash; Smart Line series với nhiều ưu điểm nhằm hạn chế tối đa b&aacute;o động giả như những sản phẩm trước đ&acirc;y. D&ograve;ng sản phẩm c&oacute; nhiều lựa chọn cho khoảng c&aacute;ch lắp đặt kh&aacute;c nhau ph&ugrave; hợp với từng y&ecirc;u cầu: 60m/100m/200m.<br /> &nbsp;</p>
<p><strong>Một số t&iacute;nh năng ch&iacute;nh:</strong></p>
<p><strong>1.C&ocirc;ng nghệ Pulse k&eacute;p</strong></p>
<p>C&aacute;c d&ograve;ng sản phẩm SL-QDM v&agrave; SL-QDP trong Smart Line series được t&iacute;ch hợp c&ocirc;ng nghệ Pulse k&eacute;p nhằm tăng cường t&iacute;n hiệu gửi v&agrave; nhận giữa hai đầu nhằm chống lại c&aacute;c nguồn nhiễu từ m&ocirc;i trường như mặt trời, &aacute;nh sang nh&acirc;n tạo. Kết hợp c&ugrave;ng với c&ocirc;ng nghệ chống &aacute;nh s&aacute;ng mặt trời ba lớp của OPTEX nhằm đảm bảo độ tin cậy cao nhất trong m&ocirc;i trường an ninh ngo&agrave;i trời.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML1.png" alt="" width="600" height="214" /></p>
<p><strong>2. 4 tia hồng ngoại độc lập</strong></p>
<p>Sử dụng c&ocirc;ng nghệ thu ph&aacute;t 4 tia hồng ngoại độc lập, nhằm giảm thiểu khả năng g&acirc;y nhiễu từ chim bay hay l&aacute; c&acirc;y rơi như những loại đầu b&aacute;o dạng 2 tia th&ocirc;ng thường.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML2.png" alt="" width="600" height="169" /></p>
<p style="text-align: left;"><strong>3.Chuẩn IP65 ngo&agrave;i trời chống nước v&agrave; bụi</strong><br /> C&aacute;c đầu b&aacute;o được nghi&ecirc;n cứu thiết kế v&agrave; chế tạo đạt chuẩn IP65 cho ph&eacute;p hoạt động hiệu quả ngo&agrave;i trời trong mọi điều kiện thời tiết kh&aacute;c nhau. C&aacute;c m&eacute;p nối giữa nắp chụp v&agrave; th&acirc;n thiết bị phủ 1 lớp gioăng cao su nhằm chống lại sự x&acirc;m nhập của nước, bụi, cũng như c&ocirc;n tr&ugrave;ng.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML3.png" alt="" width="354" height="291" /></p>
<p style="text-align: left;"><strong>C&ocirc;ng nghệ Chống &Aacute;nh S&aacute;ng Mặt Trời Ba Lớp (SL-QDM/SL-QDP)</strong><br /> Đ&acirc;y l&agrave; c&ocirc;ng nghệ được sử dụng nhằm n&acirc;ng cao hiệu quả hoạt động của cảm biến trong c&aacute;c điều kiện m&ocirc;i trường v&agrave; &aacute;nh s&aacute;ng kh&aacute;c nhau. C&ocirc;ng nghệ gồm 3 phần:<br /> (1)&nbsp;&nbsp;&nbsp; Lớp vỏ chụp được phủ chất liệu lọc đặc biệt nhằm loại bỏ &aacute;nh s&aacute;ng xuy&ecirc;n qua.<br /> (2)&nbsp;&nbsp;&nbsp; C&aacute;c thiết bị photodiode với bộ lọc IR bandpass chỉ cho ph&eacute;p c&aacute;c beam IR c&oacute; chung bước s&oacute;ng đi qua.<br /> (3)&nbsp;&nbsp;&nbsp; C&aacute;c modul bổ xung &aacute;nh s&aacute;ng nhằm ph&acirc;n biệt &aacute;nh s&aacute;ng tia IR với c&aacute;c nguồn &aacute;nh s&aacute;ng b&ecirc;n ngo&agrave;i kh&aacute;c.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML4.png" alt="" width="600" height="159" /></p>
<p style="text-align: left;"><strong>Chức năng tăng giảm cường độ của tia Beam</strong><br /> Cường độ của tia beam c&oacute; thể được điều chỉnh ph&ugrave; hợp với nhiều vị tr&iacute; v&agrave; điều kiện m&ocirc;i trường kh&aacute;c nhau nhằm giảm thiểu độ nhiễu từ m&ocirc;i trường b&ecirc;n ngo&agrave;i.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML5.png" alt="" width="600" height="257" /></p>
<p style="text-align: left;"><strong>Dễ d&agrave;ng trong việc lắp đặt</strong><br /> Một trong những vấn đề thường gặp phải khi lắp đặt h&agrave;ng r&agrave;o quang điện l&agrave; y&ecirc;u cầu bộ thu v&agrave; ph&aacute;t cần được lắp song song với nhau tr&ecirc;n một khoảng c&aacute;ch xa. Với việc t&iacute;ch hợp thấu k&iacute;nh ph&oacute;ng đại x2 tr&ecirc;n mỗi cảm biến. Smart Line series cho ph&eacute;p người lắp đặt x&aacute;c định được vị tr&iacute; lắp đặt ch&iacute;nh x&aacute;c cho từng đầu b&aacute;o.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML6.png" alt="" width="600" height="274" /></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_swu1442288876.jpg', 'Hiện nay việc sử dụng hàng rào quang điện (Photoelectric Detector) dạng Beam trong các hệ thống báo động chống đột nhập cho các khu vực rộng, yêu cầu an ninh cao như khu công nghiệp, nhà máy, khu vực quân sự, sân bay, bến cảng,…ngày càng phổ biến', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('11776956-c44d-4313-b72d-883e9ae52551', 0, 'Giải pháp quản lý trạm cân tải trọng sử dụng camera và phần mềm nhận dạng biển số', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh sử dụng Smart Line Series của Optex</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2338</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>Hiện nay việc sử dụng h&agrave;ng r&agrave;o quang điện (Photoelectric Detector) dạng Beam trong c&aacute;c hệ thống b&aacute;o động chống đột nhập cho c&aacute;c khu vực rộng, y&ecirc;u cầu an ninh cao như khu c&ocirc;ng nghiệp, nh&agrave; m&aacute;y, khu vực qu&acirc;n sự, s&acirc;n bay, bến cảng,&hellip;ng&agrave;y c&agrave;ng phổ biến. C&aacute;c cảm biến h&agrave;ng r&agrave;o quang điện cho ph&eacute;p đưa ra c&aacute;c cảnh b&aacute;o nhanh tới trung t&acirc;m an ninh khi c&oacute; đối tượng đi ngang qua c&aacute;c tia hồng ngoại đ&oacute;ng vai tr&ograve; như h&agrave;ng r&agrave;o ảo. Một trong những vẫn đề khi sử dụng h&agrave;ng r&agrave;o quang điện hay gặp phải l&agrave; hiện tượng b&aacute;o động giả từ m&ocirc;i trường xung quanh như động vật, c&acirc;y cối, &aacute;nh s&aacute;ng mặt trời cũng như &aacute;nh s&aacute;ng nh&acirc;n tạo. Hiểu r&otilde; vấn đề n&agrave;y, OPTEX một c&ocirc;ng ty chuy&ecirc;n nghi&ecirc;n cứu v&agrave; sản xuất cảm biến cho hệ thống b&aacute;o động đ&atilde; giới thiệu d&ograve;ng sản phẩm h&agrave;ng r&agrave;o quang điện thế hệ mới &ndash; Smart Line series với nhiều ưu điểm nhằm hạn chế tối đa b&aacute;o động giả như những sản phẩm trước đ&acirc;y. D&ograve;ng sản phẩm c&oacute; nhiều lựa chọn cho khoảng c&aacute;ch lắp đặt kh&aacute;c nhau ph&ugrave; hợp với từng y&ecirc;u cầu: 60m/100m/200m.<br /> &nbsp;</p>
<p><strong>Một số t&iacute;nh năng ch&iacute;nh:</strong></p>
<p><strong>1.C&ocirc;ng nghệ Pulse k&eacute;p</strong></p>
<p>C&aacute;c d&ograve;ng sản phẩm SL-QDM v&agrave; SL-QDP trong Smart Line series được t&iacute;ch hợp c&ocirc;ng nghệ Pulse k&eacute;p nhằm tăng cường t&iacute;n hiệu gửi v&agrave; nhận giữa hai đầu nhằm chống lại c&aacute;c nguồn nhiễu từ m&ocirc;i trường như mặt trời, &aacute;nh sang nh&acirc;n tạo. Kết hợp c&ugrave;ng với c&ocirc;ng nghệ chống &aacute;nh s&aacute;ng mặt trời ba lớp của OPTEX nhằm đảm bảo độ tin cậy cao nhất trong m&ocirc;i trường an ninh ngo&agrave;i trời.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML1.png" alt="" width="600" height="214" /></p>
<p><strong>2. 4 tia hồng ngoại độc lập</strong></p>
<p>Sử dụng c&ocirc;ng nghệ thu ph&aacute;t 4 tia hồng ngoại độc lập, nhằm giảm thiểu khả năng g&acirc;y nhiễu từ chim bay hay l&aacute; c&acirc;y rơi như những loại đầu b&aacute;o dạng 2 tia th&ocirc;ng thường.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML2.png" alt="" width="600" height="169" /></p>
<p style="text-align: left;"><strong>3.Chuẩn IP65 ngo&agrave;i trời chống nước v&agrave; bụi</strong><br /> C&aacute;c đầu b&aacute;o được nghi&ecirc;n cứu thiết kế v&agrave; chế tạo đạt chuẩn IP65 cho ph&eacute;p hoạt động hiệu quả ngo&agrave;i trời trong mọi điều kiện thời tiết kh&aacute;c nhau. C&aacute;c m&eacute;p nối giữa nắp chụp v&agrave; th&acirc;n thiết bị phủ 1 lớp gioăng cao su nhằm chống lại sự x&acirc;m nhập của nước, bụi, cũng như c&ocirc;n tr&ugrave;ng.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML3.png" alt="" width="354" height="291" /></p>
<p style="text-align: left;"><strong>C&ocirc;ng nghệ Chống &Aacute;nh S&aacute;ng Mặt Trời Ba Lớp (SL-QDM/SL-QDP)</strong><br /> Đ&acirc;y l&agrave; c&ocirc;ng nghệ được sử dụng nhằm n&acirc;ng cao hiệu quả hoạt động của cảm biến trong c&aacute;c điều kiện m&ocirc;i trường v&agrave; &aacute;nh s&aacute;ng kh&aacute;c nhau. C&ocirc;ng nghệ gồm 3 phần:<br /> (1)&nbsp;&nbsp;&nbsp; Lớp vỏ chụp được phủ chất liệu lọc đặc biệt nhằm loại bỏ &aacute;nh s&aacute;ng xuy&ecirc;n qua.<br /> (2)&nbsp;&nbsp;&nbsp; C&aacute;c thiết bị photodiode với bộ lọc IR bandpass chỉ cho ph&eacute;p c&aacute;c beam IR c&oacute; chung bước s&oacute;ng đi qua.<br /> (3)&nbsp;&nbsp;&nbsp; C&aacute;c modul bổ xung &aacute;nh s&aacute;ng nhằm ph&acirc;n biệt &aacute;nh s&aacute;ng tia IR với c&aacute;c nguồn &aacute;nh s&aacute;ng b&ecirc;n ngo&agrave;i kh&aacute;c.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML4.png" alt="" width="600" height="159" /></p>
<p style="text-align: left;"><strong>Chức năng tăng giảm cường độ của tia Beam</strong><br /> Cường độ của tia beam c&oacute; thể được điều chỉnh ph&ugrave; hợp với nhiều vị tr&iacute; v&agrave; điều kiện m&ocirc;i trường kh&aacute;c nhau nhằm giảm thiểu độ nhiễu từ m&ocirc;i trường b&ecirc;n ngo&agrave;i.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML5.png" alt="" width="600" height="257" /></p>
<p style="text-align: left;"><strong>Dễ d&agrave;ng trong việc lắp đặt</strong><br /> Một trong những vấn đề thường gặp phải khi lắp đặt h&agrave;ng r&agrave;o quang điện l&agrave; y&ecirc;u cầu bộ thu v&agrave; ph&aacute;t cần được lắp song song với nhau tr&ecirc;n một khoảng c&aacute;ch xa. Với việc t&iacute;ch hợp thấu k&iacute;nh ph&oacute;ng đại x2 tr&ecirc;n mỗi cảm biến. Smart Line series cho ph&eacute;p người lắp đặt x&aacute;c định được vị tr&iacute; lắp đặt ch&iacute;nh x&aacute;c cho từng đầu b&aacute;o.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML6.png" alt="" width="600" height="274" /></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_xfq1314774707.jpg', 'Nhằm mục đích tự động hóa, nâng cao hiệu suất, giảm thiểu sức lao động và tính chính xác, chống gian lận tại trạm cân tải trọng hiện nay, công ty Biển Bạc đã cho ra mắt phần mềm ứng dụng công nghệ nhận dạng biển số cho các trạm cân tải trọng.', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('4689efb0-d4da-4d16-b93f-68c65ec7d8ba', 0, 'Giải pháp giám sát từ xa lên tới 200 user truy cập đồng thời với PC BASE', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh sử dụng Smart Line Series của Optex</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2338</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>Hiện nay việc sử dụng h&agrave;ng r&agrave;o quang điện (Photoelectric Detector) dạng Beam trong c&aacute;c hệ thống b&aacute;o động chống đột nhập cho c&aacute;c khu vực rộng, y&ecirc;u cầu an ninh cao như khu c&ocirc;ng nghiệp, nh&agrave; m&aacute;y, khu vực qu&acirc;n sự, s&acirc;n bay, bến cảng,&hellip;ng&agrave;y c&agrave;ng phổ biến. C&aacute;c cảm biến h&agrave;ng r&agrave;o quang điện cho ph&eacute;p đưa ra c&aacute;c cảnh b&aacute;o nhanh tới trung t&acirc;m an ninh khi c&oacute; đối tượng đi ngang qua c&aacute;c tia hồng ngoại đ&oacute;ng vai tr&ograve; như h&agrave;ng r&agrave;o ảo. Một trong những vẫn đề khi sử dụng h&agrave;ng r&agrave;o quang điện hay gặp phải l&agrave; hiện tượng b&aacute;o động giả từ m&ocirc;i trường xung quanh như động vật, c&acirc;y cối, &aacute;nh s&aacute;ng mặt trời cũng như &aacute;nh s&aacute;ng nh&acirc;n tạo. Hiểu r&otilde; vấn đề n&agrave;y, OPTEX một c&ocirc;ng ty chuy&ecirc;n nghi&ecirc;n cứu v&agrave; sản xuất cảm biến cho hệ thống b&aacute;o động đ&atilde; giới thiệu d&ograve;ng sản phẩm h&agrave;ng r&agrave;o quang điện thế hệ mới &ndash; Smart Line series với nhiều ưu điểm nhằm hạn chế tối đa b&aacute;o động giả như những sản phẩm trước đ&acirc;y. D&ograve;ng sản phẩm c&oacute; nhiều lựa chọn cho khoảng c&aacute;ch lắp đặt kh&aacute;c nhau ph&ugrave; hợp với từng y&ecirc;u cầu: 60m/100m/200m.<br /> &nbsp;</p>
<p><strong>Một số t&iacute;nh năng ch&iacute;nh:</strong></p>
<p><strong>1.C&ocirc;ng nghệ Pulse k&eacute;p</strong></p>
<p>C&aacute;c d&ograve;ng sản phẩm SL-QDM v&agrave; SL-QDP trong Smart Line series được t&iacute;ch hợp c&ocirc;ng nghệ Pulse k&eacute;p nhằm tăng cường t&iacute;n hiệu gửi v&agrave; nhận giữa hai đầu nhằm chống lại c&aacute;c nguồn nhiễu từ m&ocirc;i trường như mặt trời, &aacute;nh sang nh&acirc;n tạo. Kết hợp c&ugrave;ng với c&ocirc;ng nghệ chống &aacute;nh s&aacute;ng mặt trời ba lớp của OPTEX nhằm đảm bảo độ tin cậy cao nhất trong m&ocirc;i trường an ninh ngo&agrave;i trời.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML1.png" alt="" width="600" height="214" /></p>
<p><strong>2. 4 tia hồng ngoại độc lập</strong></p>
<p>Sử dụng c&ocirc;ng nghệ thu ph&aacute;t 4 tia hồng ngoại độc lập, nhằm giảm thiểu khả năng g&acirc;y nhiễu từ chim bay hay l&aacute; c&acirc;y rơi như những loại đầu b&aacute;o dạng 2 tia th&ocirc;ng thường.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML2.png" alt="" width="600" height="169" /></p>
<p style="text-align: left;"><strong>3.Chuẩn IP65 ngo&agrave;i trời chống nước v&agrave; bụi</strong><br /> C&aacute;c đầu b&aacute;o được nghi&ecirc;n cứu thiết kế v&agrave; chế tạo đạt chuẩn IP65 cho ph&eacute;p hoạt động hiệu quả ngo&agrave;i trời trong mọi điều kiện thời tiết kh&aacute;c nhau. C&aacute;c m&eacute;p nối giữa nắp chụp v&agrave; th&acirc;n thiết bị phủ 1 lớp gioăng cao su nhằm chống lại sự x&acirc;m nhập của nước, bụi, cũng như c&ocirc;n tr&ugrave;ng.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML3.png" alt="" width="354" height="291" /></p>
<p style="text-align: left;"><strong>C&ocirc;ng nghệ Chống &Aacute;nh S&aacute;ng Mặt Trời Ba Lớp (SL-QDM/SL-QDP)</strong><br /> Đ&acirc;y l&agrave; c&ocirc;ng nghệ được sử dụng nhằm n&acirc;ng cao hiệu quả hoạt động của cảm biến trong c&aacute;c điều kiện m&ocirc;i trường v&agrave; &aacute;nh s&aacute;ng kh&aacute;c nhau. C&ocirc;ng nghệ gồm 3 phần:<br /> (1)&nbsp;&nbsp;&nbsp; Lớp vỏ chụp được phủ chất liệu lọc đặc biệt nhằm loại bỏ &aacute;nh s&aacute;ng xuy&ecirc;n qua.<br /> (2)&nbsp;&nbsp;&nbsp; C&aacute;c thiết bị photodiode với bộ lọc IR bandpass chỉ cho ph&eacute;p c&aacute;c beam IR c&oacute; chung bước s&oacute;ng đi qua.<br /> (3)&nbsp;&nbsp;&nbsp; C&aacute;c modul bổ xung &aacute;nh s&aacute;ng nhằm ph&acirc;n biệt &aacute;nh s&aacute;ng tia IR với c&aacute;c nguồn &aacute;nh s&aacute;ng b&ecirc;n ngo&agrave;i kh&aacute;c.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML4.png" alt="" width="600" height="159" /></p>
<p style="text-align: left;"><strong>Chức năng tăng giảm cường độ của tia Beam</strong><br /> Cường độ của tia beam c&oacute; thể được điều chỉnh ph&ugrave; hợp với nhiều vị tr&iacute; v&agrave; điều kiện m&ocirc;i trường kh&aacute;c nhau nhằm giảm thiểu độ nhiễu từ m&ocirc;i trường b&ecirc;n ngo&agrave;i.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML5.png" alt="" width="600" height="257" /></p>
<p style="text-align: left;"><strong>Dễ d&agrave;ng trong việc lắp đặt</strong><br /> Một trong những vấn đề thường gặp phải khi lắp đặt h&agrave;ng r&agrave;o quang điện l&agrave; y&ecirc;u cầu bộ thu v&agrave; ph&aacute;t cần được lắp song song với nhau tr&ecirc;n một khoảng c&aacute;ch xa. Với việc t&iacute;ch hợp thấu k&iacute;nh ph&oacute;ng đại x2 tr&ecirc;n mỗi cảm biến. Smart Line series cho ph&eacute;p người lắp đặt x&aacute;c định được vị tr&iacute; lắp đặt ch&iacute;nh x&aacute;c cho từng đầu b&aacute;o.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML6.png" alt="" width="600" height="274" /></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_wwy1318991188.jpg', 'Hiện nay đã có rất nhiều trường học , bệnh viện sử dụng camera vào việc quan sát nhằm đảm bảo an ninh cũng như đáp ứng nhu cầu quan sát theo dõi con em và bệnh nhân. Tuy nhiên các hệ thống giám sát hiện tại vẫn còn một số nhược điểm do đó chưa đáp ứng được hoàn toàn nhu cầu giám sát của các bậc phụ huynh, các bác sĩ và người nhà bệnh nhân.', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('63805980-f34b-4ee4-91f3-400076e1d2ad', 0, 'Biển Bạc giới thiệu giải pháp giám sát chuỗi cửa hàng bán lẻ', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh cho kh&aacute;ch sạn</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2289</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>&nbsp;<img src="http://bienbacsecurity.com.vn/upload_images/giai-phap-an-ninh-cho-khach-san.jpg" alt="" width="600" height="379" /></p>
<p><strong>C&aacute;c giải ph&aacute;p bao gồm:</strong><br /> - Hệ thống camera gi&aacute;m s&aacute;t<br /> - Hệ thống b&aacute;o động<br /> - Hệ thống quản l&yacute; v&agrave;o ra<br /> - Hệ thống quản l&yacute; b&atilde;i xe<br /> <strong>Cụ thể:</strong><br /> <strong>1. Hệ thống camera gi&aacute;m s&aacute;t:</strong> Gi&aacute;m s&aacute;t c&aacute;c khu vực quan trọng như đại sảnh, h&agrave;nh lang, lối tho&aacute;t hiểm&hellip; Theo d&otilde;i, ghi h&igrave;nh, cung cấp c&aacute;c bằng chứng khi c&oacute; sự việc xảy ra. T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh, hỗ trợ việc quản l&yacute; một c&aacute;ch mạnh mẽ.<br /> -&nbsp;&nbsp; &nbsp;Ghi h&igrave;nh 24/24, ghi h&igrave;nh theo sự kiện<br /> -&nbsp;&nbsp; &nbsp;Kết nối xem qua mạng LAN, Internet, 3G&hellip;<br /> -&nbsp;&nbsp; &nbsp;T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh đưa ra cảnh b&aacute;o sớm trước khi sự việc xảy ra<br /> -&nbsp;&nbsp; &nbsp;Camera độ ph&acirc;n giải cao, hỗ trợ mạnh mẽ cho việc quản l&yacute; v&agrave; điều tra<br /> <strong>2. Hệ thống quản l&yacute; b&atilde;i xe:</strong> Quản l&yacute; xe ra v&agrave;o của kh&aacute;ch, nh&acirc;n vi&ecirc;n, lập c&aacute;c b&aacute;o c&aacute;o thống k&ecirc; theo y&ecirc;u cầu quản l&yacute;.<br /> -&nbsp;&nbsp; &nbsp;Thời gian ra v&agrave;o b&atilde;i xe nhanh ch&oacute;ng, giảm t&igrave;nh trạng &ugrave;n tắc đầu v&agrave;o v&agrave; đầu ra giờ cao điểm<br /> -&nbsp;&nbsp; &nbsp;Ph&acirc;n chia c&aacute;c loại v&eacute; ng&agrave;y, th&aacute;ng r&otilde; r&agrave;ng<br /> -&nbsp;&nbsp; &nbsp;C&ocirc;ng nghệ thẻ từ đăng k&yacute; với phần mềm quản l&yacute;, chống t&igrave;nh trạng v&eacute; giả<br /> -&nbsp;&nbsp; &nbsp;Kiểm so&aacute;t lượng xe v&agrave;o ra, dễ d&agrave;ng cho việc thống k&ecirc; nguồn thu từ gửi xe<br /> <strong>3. Hệ thống quản l&yacute; v&agrave;o ra:</strong> kiểm so&aacute;t c&aacute;c cửa v&agrave;o ra, giới hạn khu vực gi&agrave;nh cho nh&acirc;n vi&ecirc;n v&agrave; kh&aacute;ch&hellip;hệ thống ki&ecirc;m lu&ocirc;n t&iacute;nh năng chấm c&ocirc;ng cho nh&acirc;n vi&ecirc;n<br /> <strong>4. Hệ thống b&aacute;o động b&aacute;o ch&aacute;y:</strong> Cảnh b&aacute;o tức th&igrave; ngay khi ph&aacute;t hiện c&aacute;c đột nhập tr&aacute;i ph&eacute;p, ph&aacute;t hiện sớm c&aacute;c vụ hỏa hoạn. Một số loại đầu b&aacute;o chuy&ecirc;n dụng với t&iacute;nh năng cảnh b&aacute;o k&iacute;nh vỡ, tr&agrave;n nước, chấn động&hellip;</p>
<p>&nbsp;C&aacute;c c&ocirc;ng tr&igrave;nh kh&aacute;ch sạn Biển Bạc đ&atilde; triển khai: <a href="http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855">http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855</a></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_agk1377231902.jpg', 'Series bài viết giới thiệu các giải pháp giám sát của hãng Nuuo – thương hiệu nổi tiếng Đài Loan cùng với các giải pháp tối ưu được tin cậy triển khai trên toàn thế giới. Phần VI: Giải pháp giám sát chuỗi cửa hàng bán lẻ, trung tâm thương mại...', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('7a79c452-4ff1-44ba-ab14-922d708581b7', 0, 'Biển Bạc giới thiệu giải pháp giám sát chuỗi cửa hàng bán lẻ', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh sử dụng Smart Line Series của Optex</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2338</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>Hiện nay việc sử dụng h&agrave;ng r&agrave;o quang điện (Photoelectric Detector) dạng Beam trong c&aacute;c hệ thống b&aacute;o động chống đột nhập cho c&aacute;c khu vực rộng, y&ecirc;u cầu an ninh cao như khu c&ocirc;ng nghiệp, nh&agrave; m&aacute;y, khu vực qu&acirc;n sự, s&acirc;n bay, bến cảng,&hellip;ng&agrave;y c&agrave;ng phổ biến. C&aacute;c cảm biến h&agrave;ng r&agrave;o quang điện cho ph&eacute;p đưa ra c&aacute;c cảnh b&aacute;o nhanh tới trung t&acirc;m an ninh khi c&oacute; đối tượng đi ngang qua c&aacute;c tia hồng ngoại đ&oacute;ng vai tr&ograve; như h&agrave;ng r&agrave;o ảo. Một trong những vẫn đề khi sử dụng h&agrave;ng r&agrave;o quang điện hay gặp phải l&agrave; hiện tượng b&aacute;o động giả từ m&ocirc;i trường xung quanh như động vật, c&acirc;y cối, &aacute;nh s&aacute;ng mặt trời cũng như &aacute;nh s&aacute;ng nh&acirc;n tạo. Hiểu r&otilde; vấn đề n&agrave;y, OPTEX một c&ocirc;ng ty chuy&ecirc;n nghi&ecirc;n cứu v&agrave; sản xuất cảm biến cho hệ thống b&aacute;o động đ&atilde; giới thiệu d&ograve;ng sản phẩm h&agrave;ng r&agrave;o quang điện thế hệ mới &ndash; Smart Line series với nhiều ưu điểm nhằm hạn chế tối đa b&aacute;o động giả như những sản phẩm trước đ&acirc;y. D&ograve;ng sản phẩm c&oacute; nhiều lựa chọn cho khoảng c&aacute;ch lắp đặt kh&aacute;c nhau ph&ugrave; hợp với từng y&ecirc;u cầu: 60m/100m/200m.<br /> &nbsp;</p>
<p><strong>Một số t&iacute;nh năng ch&iacute;nh:</strong></p>
<p><strong>1.C&ocirc;ng nghệ Pulse k&eacute;p</strong></p>
<p>C&aacute;c d&ograve;ng sản phẩm SL-QDM v&agrave; SL-QDP trong Smart Line series được t&iacute;ch hợp c&ocirc;ng nghệ Pulse k&eacute;p nhằm tăng cường t&iacute;n hiệu gửi v&agrave; nhận giữa hai đầu nhằm chống lại c&aacute;c nguồn nhiễu từ m&ocirc;i trường như mặt trời, &aacute;nh sang nh&acirc;n tạo. Kết hợp c&ugrave;ng với c&ocirc;ng nghệ chống &aacute;nh s&aacute;ng mặt trời ba lớp của OPTEX nhằm đảm bảo độ tin cậy cao nhất trong m&ocirc;i trường an ninh ngo&agrave;i trời.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML1.png" alt="" width="600" height="214" /></p>
<p><strong>2. 4 tia hồng ngoại độc lập</strong></p>
<p>Sử dụng c&ocirc;ng nghệ thu ph&aacute;t 4 tia hồng ngoại độc lập, nhằm giảm thiểu khả năng g&acirc;y nhiễu từ chim bay hay l&aacute; c&acirc;y rơi như những loại đầu b&aacute;o dạng 2 tia th&ocirc;ng thường.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML2.png" alt="" width="600" height="169" /></p>
<p style="text-align: left;"><strong>3.Chuẩn IP65 ngo&agrave;i trời chống nước v&agrave; bụi</strong><br /> C&aacute;c đầu b&aacute;o được nghi&ecirc;n cứu thiết kế v&agrave; chế tạo đạt chuẩn IP65 cho ph&eacute;p hoạt động hiệu quả ngo&agrave;i trời trong mọi điều kiện thời tiết kh&aacute;c nhau. C&aacute;c m&eacute;p nối giữa nắp chụp v&agrave; th&acirc;n thiết bị phủ 1 lớp gioăng cao su nhằm chống lại sự x&acirc;m nhập của nước, bụi, cũng như c&ocirc;n tr&ugrave;ng.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML3.png" alt="" width="354" height="291" /></p>
<p style="text-align: left;"><strong>C&ocirc;ng nghệ Chống &Aacute;nh S&aacute;ng Mặt Trời Ba Lớp (SL-QDM/SL-QDP)</strong><br /> Đ&acirc;y l&agrave; c&ocirc;ng nghệ được sử dụng nhằm n&acirc;ng cao hiệu quả hoạt động của cảm biến trong c&aacute;c điều kiện m&ocirc;i trường v&agrave; &aacute;nh s&aacute;ng kh&aacute;c nhau. C&ocirc;ng nghệ gồm 3 phần:<br /> (1)&nbsp;&nbsp;&nbsp; Lớp vỏ chụp được phủ chất liệu lọc đặc biệt nhằm loại bỏ &aacute;nh s&aacute;ng xuy&ecirc;n qua.<br /> (2)&nbsp;&nbsp;&nbsp; C&aacute;c thiết bị photodiode với bộ lọc IR bandpass chỉ cho ph&eacute;p c&aacute;c beam IR c&oacute; chung bước s&oacute;ng đi qua.<br /> (3)&nbsp;&nbsp;&nbsp; C&aacute;c modul bổ xung &aacute;nh s&aacute;ng nhằm ph&acirc;n biệt &aacute;nh s&aacute;ng tia IR với c&aacute;c nguồn &aacute;nh s&aacute;ng b&ecirc;n ngo&agrave;i kh&aacute;c.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML4.png" alt="" width="600" height="159" /></p>
<p style="text-align: left;"><strong>Chức năng tăng giảm cường độ của tia Beam</strong><br /> Cường độ của tia beam c&oacute; thể được điều chỉnh ph&ugrave; hợp với nhiều vị tr&iacute; v&agrave; điều kiện m&ocirc;i trường kh&aacute;c nhau nhằm giảm thiểu độ nhiễu từ m&ocirc;i trường b&ecirc;n ngo&agrave;i.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML5.png" alt="" width="600" height="257" /></p>
<p style="text-align: left;"><strong>Dễ d&agrave;ng trong việc lắp đặt</strong><br /> Một trong những vấn đề thường gặp phải khi lắp đặt h&agrave;ng r&agrave;o quang điện l&agrave; y&ecirc;u cầu bộ thu v&agrave; ph&aacute;t cần được lắp song song với nhau tr&ecirc;n một khoảng c&aacute;ch xa. Với việc t&iacute;ch hợp thấu k&iacute;nh ph&oacute;ng đại x2 tr&ecirc;n mỗi cảm biến. Smart Line series cho ph&eacute;p người lắp đặt x&aacute;c định được vị tr&iacute; lắp đặt ch&iacute;nh x&aacute;c cho từng đầu b&aacute;o.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML6.png" alt="" width="600" height="274" /></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_bzo1391997364.jpg', 'Hệ thống an ninh siêu thị - thư viện là hệ thống ngăn ngừa tình trạng thất thoát hàng hóa do do khách, nhân viên…tại cửa hàng. Các hệ thống hiện đại còn hỗ trợ các tính năng thông minh như đếm số lượng khách ra vào.', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('8154bbdc-6f55-4cd7-b05b-3b23ebe99211', 0, 'Giải pháp quản lý vào ra sử dụng công nghệ nhận dạng biển số của Biển Bạc', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh cho kh&aacute;ch sạn</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2289</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>&nbsp;<img src="http://bienbacsecurity.com.vn/upload_images/giai-phap-an-ninh-cho-khach-san.jpg" alt="" width="600" height="379" /></p>
<p><strong>C&aacute;c giải ph&aacute;p bao gồm:</strong><br /> - Hệ thống camera gi&aacute;m s&aacute;t<br /> - Hệ thống b&aacute;o động<br /> - Hệ thống quản l&yacute; v&agrave;o ra<br /> - Hệ thống quản l&yacute; b&atilde;i xe<br /> <strong>Cụ thể:</strong><br /> <strong>1. Hệ thống camera gi&aacute;m s&aacute;t:</strong> Gi&aacute;m s&aacute;t c&aacute;c khu vực quan trọng như đại sảnh, h&agrave;nh lang, lối tho&aacute;t hiểm&hellip; Theo d&otilde;i, ghi h&igrave;nh, cung cấp c&aacute;c bằng chứng khi c&oacute; sự việc xảy ra. T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh, hỗ trợ việc quản l&yacute; một c&aacute;ch mạnh mẽ.<br /> -&nbsp;&nbsp; &nbsp;Ghi h&igrave;nh 24/24, ghi h&igrave;nh theo sự kiện<br /> -&nbsp;&nbsp; &nbsp;Kết nối xem qua mạng LAN, Internet, 3G&hellip;<br /> -&nbsp;&nbsp; &nbsp;T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh đưa ra cảnh b&aacute;o sớm trước khi sự việc xảy ra<br /> -&nbsp;&nbsp; &nbsp;Camera độ ph&acirc;n giải cao, hỗ trợ mạnh mẽ cho việc quản l&yacute; v&agrave; điều tra<br /> <strong>2. Hệ thống quản l&yacute; b&atilde;i xe:</strong> Quản l&yacute; xe ra v&agrave;o của kh&aacute;ch, nh&acirc;n vi&ecirc;n, lập c&aacute;c b&aacute;o c&aacute;o thống k&ecirc; theo y&ecirc;u cầu quản l&yacute;.<br /> -&nbsp;&nbsp; &nbsp;Thời gian ra v&agrave;o b&atilde;i xe nhanh ch&oacute;ng, giảm t&igrave;nh trạng &ugrave;n tắc đầu v&agrave;o v&agrave; đầu ra giờ cao điểm<br /> -&nbsp;&nbsp; &nbsp;Ph&acirc;n chia c&aacute;c loại v&eacute; ng&agrave;y, th&aacute;ng r&otilde; r&agrave;ng<br /> -&nbsp;&nbsp; &nbsp;C&ocirc;ng nghệ thẻ từ đăng k&yacute; với phần mềm quản l&yacute;, chống t&igrave;nh trạng v&eacute; giả<br /> -&nbsp;&nbsp; &nbsp;Kiểm so&aacute;t lượng xe v&agrave;o ra, dễ d&agrave;ng cho việc thống k&ecirc; nguồn thu từ gửi xe<br /> <strong>3. Hệ thống quản l&yacute; v&agrave;o ra:</strong> kiểm so&aacute;t c&aacute;c cửa v&agrave;o ra, giới hạn khu vực gi&agrave;nh cho nh&acirc;n vi&ecirc;n v&agrave; kh&aacute;ch&hellip;hệ thống ki&ecirc;m lu&ocirc;n t&iacute;nh năng chấm c&ocirc;ng cho nh&acirc;n vi&ecirc;n<br /> <strong>4. Hệ thống b&aacute;o động b&aacute;o ch&aacute;y:</strong> Cảnh b&aacute;o tức th&igrave; ngay khi ph&aacute;t hiện c&aacute;c đột nhập tr&aacute;i ph&eacute;p, ph&aacute;t hiện sớm c&aacute;c vụ hỏa hoạn. Một số loại đầu b&aacute;o chuy&ecirc;n dụng với t&iacute;nh năng cảnh b&aacute;o k&iacute;nh vỡ, tr&agrave;n nước, chấn động&hellip;</p>
<p>&nbsp;C&aacute;c c&ocirc;ng tr&igrave;nh kh&aacute;ch sạn Biển Bạc đ&atilde; triển khai: <a href="http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855">http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855</a></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_wng1314765280.jpg', 'SAC (Silversea ANPR Access Control) là giải pháp quản lý vào ra sử dụng công nghệ nhận dạng biển số xe tự động. Hệ thống cho phép quản lý, giám sát, thống kê phương tiện vào, ra bao gồm cả xe máy và xe ô tô bằng hình ảnh và dữ liệu biển số xe dạng Text.', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('98ff04f8-4e71-4ad0-a5ef-0e374da41123', 0, 'Giải pháp quản lý bãi đỗ xe, bãi gửi xe thông minh của Biển Bạc', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh cho kh&aacute;ch sạn</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2289</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>&nbsp;<img src="http://bienbacsecurity.com.vn/upload_images/giai-phap-an-ninh-cho-khach-san.jpg" alt="" width="600" height="379" /></p>
<p><strong>C&aacute;c giải ph&aacute;p bao gồm:</strong><br /> - Hệ thống camera gi&aacute;m s&aacute;t<br /> - Hệ thống b&aacute;o động<br /> - Hệ thống quản l&yacute; v&agrave;o ra<br /> - Hệ thống quản l&yacute; b&atilde;i xe<br /> <strong>Cụ thể:</strong><br /> <strong>1. Hệ thống camera gi&aacute;m s&aacute;t:</strong> Gi&aacute;m s&aacute;t c&aacute;c khu vực quan trọng như đại sảnh, h&agrave;nh lang, lối tho&aacute;t hiểm&hellip; Theo d&otilde;i, ghi h&igrave;nh, cung cấp c&aacute;c bằng chứng khi c&oacute; sự việc xảy ra. T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh, hỗ trợ việc quản l&yacute; một c&aacute;ch mạnh mẽ.<br /> -&nbsp;&nbsp; &nbsp;Ghi h&igrave;nh 24/24, ghi h&igrave;nh theo sự kiện<br /> -&nbsp;&nbsp; &nbsp;Kết nối xem qua mạng LAN, Internet, 3G&hellip;<br /> -&nbsp;&nbsp; &nbsp;T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh đưa ra cảnh b&aacute;o sớm trước khi sự việc xảy ra<br /> -&nbsp;&nbsp; &nbsp;Camera độ ph&acirc;n giải cao, hỗ trợ mạnh mẽ cho việc quản l&yacute; v&agrave; điều tra<br /> <strong>2. Hệ thống quản l&yacute; b&atilde;i xe:</strong> Quản l&yacute; xe ra v&agrave;o của kh&aacute;ch, nh&acirc;n vi&ecirc;n, lập c&aacute;c b&aacute;o c&aacute;o thống k&ecirc; theo y&ecirc;u cầu quản l&yacute;.<br /> -&nbsp;&nbsp; &nbsp;Thời gian ra v&agrave;o b&atilde;i xe nhanh ch&oacute;ng, giảm t&igrave;nh trạng &ugrave;n tắc đầu v&agrave;o v&agrave; đầu ra giờ cao điểm<br /> -&nbsp;&nbsp; &nbsp;Ph&acirc;n chia c&aacute;c loại v&eacute; ng&agrave;y, th&aacute;ng r&otilde; r&agrave;ng<br /> -&nbsp;&nbsp; &nbsp;C&ocirc;ng nghệ thẻ từ đăng k&yacute; với phần mềm quản l&yacute;, chống t&igrave;nh trạng v&eacute; giả<br /> -&nbsp;&nbsp; &nbsp;Kiểm so&aacute;t lượng xe v&agrave;o ra, dễ d&agrave;ng cho việc thống k&ecirc; nguồn thu từ gửi xe<br /> <strong>3. Hệ thống quản l&yacute; v&agrave;o ra:</strong> kiểm so&aacute;t c&aacute;c cửa v&agrave;o ra, giới hạn khu vực gi&agrave;nh cho nh&acirc;n vi&ecirc;n v&agrave; kh&aacute;ch&hellip;hệ thống ki&ecirc;m lu&ocirc;n t&iacute;nh năng chấm c&ocirc;ng cho nh&acirc;n vi&ecirc;n<br /> <strong>4. Hệ thống b&aacute;o động b&aacute;o ch&aacute;y:</strong> Cảnh b&aacute;o tức th&igrave; ngay khi ph&aacute;t hiện c&aacute;c đột nhập tr&aacute;i ph&eacute;p, ph&aacute;t hiện sớm c&aacute;c vụ hỏa hoạn. Một số loại đầu b&aacute;o chuy&ecirc;n dụng với t&iacute;nh năng cảnh b&aacute;o k&iacute;nh vỡ, tr&agrave;n nước, chấn động&hellip;</p>
<p>&nbsp;C&aacute;c c&ocirc;ng tr&igrave;nh kh&aacute;ch sạn Biển Bạc đ&atilde; triển khai: <a href="http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855">http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855</a></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_qag1343443005.jpg', 'SPM là giải pháp quản lý bãi đỗ xe của công ty cổ phần Biển Bạc được phát triển nhằm mục đích nâng cao hiệu quả và mức độ tin cậy của các bãi đỗ xe hiện nay. Giải pháp sử dụng công nghệ nhận dạng biển số xe kết hợp với công nghệ thẻ không tiếp xúc giúp cho việc vận hành bãi xe trở nên đơn giản, nhanh chóng và hiệu quả.', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('e6a5d6e1-98f8-4464-a7bf-9be4102e9de4', 0, 'Giải pháp phát hiện và xử phạt vi phạm giao thông bằng hình ảnh STM01', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh sử dụng Smart Line Series của Optex</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2338</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>Hiện nay việc sử dụng h&agrave;ng r&agrave;o quang điện (Photoelectric Detector) dạng Beam trong c&aacute;c hệ thống b&aacute;o động chống đột nhập cho c&aacute;c khu vực rộng, y&ecirc;u cầu an ninh cao như khu c&ocirc;ng nghiệp, nh&agrave; m&aacute;y, khu vực qu&acirc;n sự, s&acirc;n bay, bến cảng,&hellip;ng&agrave;y c&agrave;ng phổ biến. C&aacute;c cảm biến h&agrave;ng r&agrave;o quang điện cho ph&eacute;p đưa ra c&aacute;c cảnh b&aacute;o nhanh tới trung t&acirc;m an ninh khi c&oacute; đối tượng đi ngang qua c&aacute;c tia hồng ngoại đ&oacute;ng vai tr&ograve; như h&agrave;ng r&agrave;o ảo. Một trong những vẫn đề khi sử dụng h&agrave;ng r&agrave;o quang điện hay gặp phải l&agrave; hiện tượng b&aacute;o động giả từ m&ocirc;i trường xung quanh như động vật, c&acirc;y cối, &aacute;nh s&aacute;ng mặt trời cũng như &aacute;nh s&aacute;ng nh&acirc;n tạo. Hiểu r&otilde; vấn đề n&agrave;y, OPTEX một c&ocirc;ng ty chuy&ecirc;n nghi&ecirc;n cứu v&agrave; sản xuất cảm biến cho hệ thống b&aacute;o động đ&atilde; giới thiệu d&ograve;ng sản phẩm h&agrave;ng r&agrave;o quang điện thế hệ mới &ndash; Smart Line series với nhiều ưu điểm nhằm hạn chế tối đa b&aacute;o động giả như những sản phẩm trước đ&acirc;y. D&ograve;ng sản phẩm c&oacute; nhiều lựa chọn cho khoảng c&aacute;ch lắp đặt kh&aacute;c nhau ph&ugrave; hợp với từng y&ecirc;u cầu: 60m/100m/200m.<br /> &nbsp;</p>
<p><strong>Một số t&iacute;nh năng ch&iacute;nh:</strong></p>
<p><strong>1.C&ocirc;ng nghệ Pulse k&eacute;p</strong></p>
<p>C&aacute;c d&ograve;ng sản phẩm SL-QDM v&agrave; SL-QDP trong Smart Line series được t&iacute;ch hợp c&ocirc;ng nghệ Pulse k&eacute;p nhằm tăng cường t&iacute;n hiệu gửi v&agrave; nhận giữa hai đầu nhằm chống lại c&aacute;c nguồn nhiễu từ m&ocirc;i trường như mặt trời, &aacute;nh sang nh&acirc;n tạo. Kết hợp c&ugrave;ng với c&ocirc;ng nghệ chống &aacute;nh s&aacute;ng mặt trời ba lớp của OPTEX nhằm đảm bảo độ tin cậy cao nhất trong m&ocirc;i trường an ninh ngo&agrave;i trời.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML1.png" alt="" width="600" height="214" /></p>
<p><strong>2. 4 tia hồng ngoại độc lập</strong></p>
<p>Sử dụng c&ocirc;ng nghệ thu ph&aacute;t 4 tia hồng ngoại độc lập, nhằm giảm thiểu khả năng g&acirc;y nhiễu từ chim bay hay l&aacute; c&acirc;y rơi như những loại đầu b&aacute;o dạng 2 tia th&ocirc;ng thường.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML2.png" alt="" width="600" height="169" /></p>
<p style="text-align: left;"><strong>3.Chuẩn IP65 ngo&agrave;i trời chống nước v&agrave; bụi</strong><br /> C&aacute;c đầu b&aacute;o được nghi&ecirc;n cứu thiết kế v&agrave; chế tạo đạt chuẩn IP65 cho ph&eacute;p hoạt động hiệu quả ngo&agrave;i trời trong mọi điều kiện thời tiết kh&aacute;c nhau. C&aacute;c m&eacute;p nối giữa nắp chụp v&agrave; th&acirc;n thiết bị phủ 1 lớp gioăng cao su nhằm chống lại sự x&acirc;m nhập của nước, bụi, cũng như c&ocirc;n tr&ugrave;ng.</p>
<p style="text-align: center;"><br /> <img src="http://bienbacsecurity.com.vn/upload_images/SML3.png" alt="" width="354" height="291" /></p>
<p style="text-align: left;"><strong>C&ocirc;ng nghệ Chống &Aacute;nh S&aacute;ng Mặt Trời Ba Lớp (SL-QDM/SL-QDP)</strong><br /> Đ&acirc;y l&agrave; c&ocirc;ng nghệ được sử dụng nhằm n&acirc;ng cao hiệu quả hoạt động của cảm biến trong c&aacute;c điều kiện m&ocirc;i trường v&agrave; &aacute;nh s&aacute;ng kh&aacute;c nhau. C&ocirc;ng nghệ gồm 3 phần:<br /> (1)&nbsp;&nbsp;&nbsp; Lớp vỏ chụp được phủ chất liệu lọc đặc biệt nhằm loại bỏ &aacute;nh s&aacute;ng xuy&ecirc;n qua.<br /> (2)&nbsp;&nbsp;&nbsp; C&aacute;c thiết bị photodiode với bộ lọc IR bandpass chỉ cho ph&eacute;p c&aacute;c beam IR c&oacute; chung bước s&oacute;ng đi qua.<br /> (3)&nbsp;&nbsp;&nbsp; C&aacute;c modul bổ xung &aacute;nh s&aacute;ng nhằm ph&acirc;n biệt &aacute;nh s&aacute;ng tia IR với c&aacute;c nguồn &aacute;nh s&aacute;ng b&ecirc;n ngo&agrave;i kh&aacute;c.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML4.png" alt="" width="600" height="159" /></p>
<p style="text-align: left;"><strong>Chức năng tăng giảm cường độ của tia Beam</strong><br /> Cường độ của tia beam c&oacute; thể được điều chỉnh ph&ugrave; hợp với nhiều vị tr&iacute; v&agrave; điều kiện m&ocirc;i trường kh&aacute;c nhau nhằm giảm thiểu độ nhiễu từ m&ocirc;i trường b&ecirc;n ngo&agrave;i.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML5.png" alt="" width="600" height="257" /></p>
<p style="text-align: left;"><strong>Dễ d&agrave;ng trong việc lắp đặt</strong><br /> Một trong những vấn đề thường gặp phải khi lắp đặt h&agrave;ng r&agrave;o quang điện l&agrave; y&ecirc;u cầu bộ thu v&agrave; ph&aacute;t cần được lắp song song với nhau tr&ecirc;n một khoảng c&aacute;ch xa. Với việc t&iacute;ch hợp thấu k&iacute;nh ph&oacute;ng đại x2 tr&ecirc;n mỗi cảm biến. Smart Line series cho ph&eacute;p người lắp đặt x&aacute;c định được vị tr&iacute; lắp đặt ch&iacute;nh x&aacute;c cho từng đầu b&aacute;o.</p>
<p style="text-align: center;"><img src="http://bienbacsecurity.com.vn/upload_images/SML6.png" alt="" width="600" height="274" /></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_sqr1399438619.jpg', 'Trong những năm qua, tình trạng giao thông ùn tắc, hỗn loạn, phóng nhanh vượt ẩu, đi sai làn, ngược chiều, tai nạn giao thông… luôn là vấn đề nổi cộm và thường xuyên được nhắc đến.', '2018-03-14 20:28:11', null, null, null, null, null);
INSERT INTO myapp.solution (id, version, tieu_de, is_deleted, ngay_tao, last_modified_user, noi_dung_chi_tiet, hinh_anh, noi_dung_ngan, last_modified_time, phone, address, comment, name, email) VALUES ('ef5ccc09-9cb0-47dc-a59b-898f893a8c04', 0, 'Giải pháp an ninh cho khách sạn', false, '2018-03-14 20:28:11', 'Admin', '<h1 id="detailnews" class="titledetail">Giải ph&aacute;p an ninh cho kh&aacute;ch sạn</h1>
<div class="clear">&nbsp;</div>
<div class="news_hits"><span class="blue">&nbsp;&nbsp;Lượt xem:</span>&nbsp;&nbsp;<span class="grey">2289</span></div>
<div class="clear">&nbsp;</div>
<div class="detailnews">
<p>&nbsp;<img src="http://bienbacsecurity.com.vn/upload_images/giai-phap-an-ninh-cho-khach-san.jpg" alt="" width="600" height="379" /></p>
<p><strong>C&aacute;c giải ph&aacute;p bao gồm:</strong><br /> - Hệ thống camera gi&aacute;m s&aacute;t<br /> - Hệ thống b&aacute;o động<br /> - Hệ thống quản l&yacute; v&agrave;o ra<br /> - Hệ thống quản l&yacute; b&atilde;i xe<br /> <strong>Cụ thể:</strong><br /> <strong>1. Hệ thống camera gi&aacute;m s&aacute;t:</strong> Gi&aacute;m s&aacute;t c&aacute;c khu vực quan trọng như đại sảnh, h&agrave;nh lang, lối tho&aacute;t hiểm&hellip; Theo d&otilde;i, ghi h&igrave;nh, cung cấp c&aacute;c bằng chứng khi c&oacute; sự việc xảy ra. T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh, hỗ trợ việc quản l&yacute; một c&aacute;ch mạnh mẽ.<br /> -&nbsp;&nbsp; &nbsp;Ghi h&igrave;nh 24/24, ghi h&igrave;nh theo sự kiện<br /> -&nbsp;&nbsp; &nbsp;Kết nối xem qua mạng LAN, Internet, 3G&hellip;<br /> -&nbsp;&nbsp; &nbsp;T&iacute;ch hợp c&aacute;c t&iacute;nh năng th&ocirc;ng minh đưa ra cảnh b&aacute;o sớm trước khi sự việc xảy ra<br /> -&nbsp;&nbsp; &nbsp;Camera độ ph&acirc;n giải cao, hỗ trợ mạnh mẽ cho việc quản l&yacute; v&agrave; điều tra<br /> <strong>2. Hệ thống quản l&yacute; b&atilde;i xe:</strong> Quản l&yacute; xe ra v&agrave;o của kh&aacute;ch, nh&acirc;n vi&ecirc;n, lập c&aacute;c b&aacute;o c&aacute;o thống k&ecirc; theo y&ecirc;u cầu quản l&yacute;.<br /> -&nbsp;&nbsp; &nbsp;Thời gian ra v&agrave;o b&atilde;i xe nhanh ch&oacute;ng, giảm t&igrave;nh trạng &ugrave;n tắc đầu v&agrave;o v&agrave; đầu ra giờ cao điểm<br /> -&nbsp;&nbsp; &nbsp;Ph&acirc;n chia c&aacute;c loại v&eacute; ng&agrave;y, th&aacute;ng r&otilde; r&agrave;ng<br /> -&nbsp;&nbsp; &nbsp;C&ocirc;ng nghệ thẻ từ đăng k&yacute; với phần mềm quản l&yacute;, chống t&igrave;nh trạng v&eacute; giả<br /> -&nbsp;&nbsp; &nbsp;Kiểm so&aacute;t lượng xe v&agrave;o ra, dễ d&agrave;ng cho việc thống k&ecirc; nguồn thu từ gửi xe<br /> <strong>3. Hệ thống quản l&yacute; v&agrave;o ra:</strong> kiểm so&aacute;t c&aacute;c cửa v&agrave;o ra, giới hạn khu vực gi&agrave;nh cho nh&acirc;n vi&ecirc;n v&agrave; kh&aacute;ch&hellip;hệ thống ki&ecirc;m lu&ocirc;n t&iacute;nh năng chấm c&ocirc;ng cho nh&acirc;n vi&ecirc;n<br /> <strong>4. Hệ thống b&aacute;o động b&aacute;o ch&aacute;y:</strong> Cảnh b&aacute;o tức th&igrave; ngay khi ph&aacute;t hiện c&aacute;c đột nhập tr&aacute;i ph&eacute;p, ph&aacute;t hiện sớm c&aacute;c vụ hỏa hoạn. Một số loại đầu b&aacute;o chuy&ecirc;n dụng với t&iacute;nh năng cảnh b&aacute;o k&iacute;nh vỡ, tr&agrave;n nước, chấn động&hellip;</p>
<p>&nbsp;C&aacute;c c&ocirc;ng tr&igrave;nh kh&aacute;ch sạn Biển Bạc đ&atilde; triển khai: <a href="http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855">http://bienbacsecurity.com.vn/en/Cong-trinh-tieu-bieu-n958/Tong-hop-danh-sach-cac-khach-san-su-dung-he-thong-an-ninh-do-Bien-Bac-cung-cap-d855</a></p>
</div>', 'http://bienbacsecurity.com.vn/pictures/small_xpg1441419749.jpg', 'Tổng hợp các giải pháp đảm bảo an ninh cho khách sạn do công ty CP Biển Bạc cung cấp và triển khai thành công tại nhiều khách sạn trên cả nước', '2018-03-14 20:28:11', null, null, null, null, null);